import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Herosection from "./herosection";

export default function Home() {
	return (
		<div>
			<Head>
				<title>Responsive Nextjs Image</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/pro.ico" />
			</Head>
			<Herosection />
			<Footer />
		</div>
	);
}
